"""add pending_action to messages

Revision ID: 149f8d406bb7
Revises: 7a1565dafc11
Create Date: 2026-05-02 20:35:43.919351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149f8d406bb7'
down_revision: Union[str, None] = '7a1565dafc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add status with a default so existing rows get 'active'
    op.add_column('medications', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('medications', sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('pending_action', sa.Text(), nullable=True))
    # Remove the server_default after backfill so new rows must explicitly set it
    op.alter_column('medications', 'status', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'pending_action')
    op.drop_column('medications', 'paused_until')
    op.drop_column('medications', 'status')
    # ### end Alembic commands ###
