"""add bot_reply to messages

Revision ID: 7a1565dafc11
Revises: ee2df62e815f
Create Date: 2026-04-14 10:58:07.183840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1565dafc11'
down_revision: Union[str, None] = 'ee2df62e815f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('bot_reply', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'bot_reply')
    # ### end Alembic commands ###
